uniform.float.vignette = 0.2
uniform.float.ambient = 0.01
uniform.float.raySpread = 0.1
uniform.float.exposure = 2.0
uniform.float.acc_power = 200
uniform.float.directEmissionStength = 2
uniform.float.blockEmissionStength = 10
clouds=off
moon=off
sun=off